---
- name: Add datadog agent user dd-agent to varnish group
  user:
    name: "{{ datadog_agent_user_name }}"
    append: yes
    groups: varnish

- name: Install datadog agent config for varnish
  copy:
    backup: yes
    content: "{{ datadog_agent_varnish_config | to_nice_yaml }}"
    mode: 0440
    owner: "{{ datadog_agent_user_name }}"
    group: "{{ datadog_agent_user_group }}"
    dest: /etc/datadog-agent/conf.d/varnish.d/conf.yaml
  register: install_agent_config

# TODO this doesn't seem to be necessary for the user to run varnishadm,
# but the datadog agent's varnish integration requires it: 
# https://github.com/DataDog/integrations-core/blob/master/varnish/datadog_checks/varnish/varnish.py#L146-L147
- name: Datadog agent user may run varnishadm with priviledges
  copy:
    dest: /etc/sudoers.d/29_datadog
    mode: 0440
    content: |
      # Ansible managed
      dd-agent ALL=(ALL) NOPASSWD:/usr/bin/varnishadm

- name: Restart Datadog agent
  service: name=datadog-agent state=restarted
  when: install_agent_config is changed
